"""
Convert the trained Keras model to a fully INT8-quantized TFLite
model, then emit C headers for firmware/vision_node.

Usage:
    python convert_tflite.py
"""
import pathlib
import json

import numpy as np
import tensorflow as tf
from tensorflow import keras

MODELS_DIR = pathlib.Path(__file__).resolve().parent.parent / "models"
DATA_DIR = pathlib.Path(__file__).resolve().parent.parent / "data" / "raw"
FIRMWARE_DIR = (
    pathlib.Path(__file__).resolve().parent.parent.parent / "firmware" / "vision_node"
)

with open(MODELS_DIR / "training_metadata.json") as f:
    metadata = json.load(f)

IMG_SIZE = tuple(metadata["image_size"])


def representative_dataset():
    count = 0
    for class_dir in sorted(DATA_DIR.iterdir()):
        if not class_dir.is_dir():
            continue
        for img_path in list(class_dir.glob("*.jpg"))[:25]:
            img = keras.utils.load_img(img_path, target_size=IMG_SIZE)
            arr = keras.utils.img_to_array(img) / 255.0
            arr = np.expand_dims(arr, axis=0).astype(np.float32)
            yield [arr]
            count += 1
    print(f"Representative dataset: {count} samples")


def main():
    model = keras.models.load_model(MODELS_DIR / "tomato_disease_model.keras")

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    tflite_path = MODELS_DIR / "tomato_disease_model_int8.tflite"
    tflite_path.write_bytes(tflite_model)
    size_kb = len(tflite_model) / 1024
    print(f"Wrote {tflite_path} ({size_kb:.1f} KB)")

    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]
    in_scale, in_zero_point = input_details["quantization"]

    correct = 0
    total = 0
    for class_idx, class_name in enumerate(metadata["class_names"]):
        class_dir = DATA_DIR / class_name
        sample_paths = list(class_dir.glob("*.jpg"))[-15:]
        for img_path in sample_paths:
            img = keras.utils.load_img(img_path, target_size=IMG_SIZE)
            arr = keras.utils.img_to_array(img) / 255.0
            arr = arr / in_scale + in_zero_point
            arr = np.clip(arr, -128, 127).astype(np.int8)
            arr = np.expand_dims(arr, axis=0)

            interpreter.set_tensor(input_details["index"], arr)
            interpreter.invoke()
            out = interpreter.get_tensor(output_details["index"])[0]
            pred = int(np.argmax(out))

            total += 1
            correct += int(pred == class_idx)

    quant_acc = correct / total if total else 0.0
    print(f"Quantized model spot-check accuracy on {total} held-out images: {quant_acc:.3f}")

    metadata["quantized_model_kb"] = round(size_kb, 1)
    metadata["quantized_spotcheck_accuracy"] = round(quant_acc, 3)
    metadata["input_quantization"] = {"scale": float(in_scale), "zero_point": int(in_zero_point)}
    with open(MODELS_DIR / "training_metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)

    FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)
    header_path = FIRMWARE_DIR / "model_data.h"
    var_name = "g_tomato_disease_model"
    with open(header_path, "w") as f:
        f.write("// Auto-generated by ml/scripts/convert_tflite.py -- do not edit by hand.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"alignas(8) const unsigned char {var_name}[] = {{\n")
        for i in range(0, len(tflite_model), 12):
            chunk = tflite_model[i : i + 12]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"  {line},\n")
        f.write("};\n\n")
        f.write(f"const unsigned int {var_name}_len = {len(tflite_model)};\n")
    print(f"Wrote {header_path} ({header_path.stat().st_size / 1024:.1f} KB source)")

    labels_path = FIRMWARE_DIR / "class_labels.h"
    with open(labels_path, "w") as f:
        f.write("// Auto-generated by ml/scripts/convert_tflite.py -- do not edit by hand.\n")
        f.write("#pragma once\n\n")
        f.write(f"constexpr int kNumClasses = {len(metadata['class_names'])};\n")
        f.write("constexpr const char* kClassLabels[kNumClasses] = {\n")
        for name in metadata["class_names"]:
            f.write(f'  "{name}",\n')
        f.write("};\n\n")
        f.write(f"constexpr int kInputWidth = {IMG_SIZE[0]};\n")
        f.write(f"constexpr int kInputHeight = {IMG_SIZE[1]};\n")
        f.write("constexpr int kInputChannels = 3;\n")
        f.write(f"constexpr float kInputScale = {float(in_scale)}f;\n")
        f.write(f"constexpr int kInputZeroPoint = {int(in_zero_point)};\n")
    print(f"Wrote {labels_path}")


if __name__ == "__main__":
    main()
