// Auto-generated by ml/scripts/convert_tflite.py -- do not edit by hand.
#pragma once

constexpr int kNumClasses = 8;
constexpr const char* kClassLabels[kNumClasses] = {
  "Bacterial_Spot",
  "Early_Blight",
  "Healthy",
  "Late_Blight",
  "Septoria_Leaf_Spot",
  "Spider_Mite",
  "TYLCV",
  "Target_Spot",
};

constexpr int kInputWidth = 96;
constexpr int kInputHeight = 96;
constexpr int kInputChannels = 3;
constexpr float kInputScale = 0.003921568859368563f;
constexpr int kInputZeroPoint = -128;
